// This will be generated by Supabase CLI
// Run: npm run db:types after setting up your Supabase project

export interface Database {
    public: {
      Tables: Record<string, unknown>
      Views: Record<string, unknown>
      Functions: Record<string, unknown>
      Enums: Record<string, unknown>
    }
  }